table app_employees_credentialtype
	lineageTag: d0d8708f-ea25-4150-a793-41571fb9234e

	column credential_id
		dataType: int64
		formatString: 0
		lineageTag: 9a506bae-116e-4c7f-b776-3d0c9bf0ba3f
		summarizeBy: none
		sourceColumn: credential_id

		annotation SummarizationSetBy = Automatic

	column credential_name
		dataType: string
		lineageTag: d634853e-b3de-40e5-825f-b19eab62469f
		summarizeBy: none
		sourceColumn: credential_name

		annotation SummarizationSetBy = Automatic

	partition app_employees_credentialtype = m
		mode: import
		queryGroup: dimension
		source =
				let
				    Source = Odbc.DataSource(Source_odbc, [HierarchicalNavigation=true]),
				    defaultdb_Database = Source{[Name=Database,Kind="Database"]}[Data],
				    public_Schema = defaultdb_Database{[Name="public",Kind="Schema"]}[Data],
				    app_employees_credentialtype_Table = public_Schema{[Name="app_employees_credentialtype",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(app_employees_credentialtype_Table,{"id", "name"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"name", "credential_name"}, {"id", "credential_id"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

