table app_employees_workbase
	lineageTag: dd84809d-82c7-49bc-8265-e4b17e0ccb1d

	column workbase_id
		dataType: int64
		formatString: 0
		lineageTag: 26d9ebc4-0740-40a3-82f8-9a42b32e23de
		summarizeBy: none
		sourceColumn: workbase_id

		annotation SummarizationSetBy = Automatic

	column workbase_name
		dataType: string
		lineageTag: e05be07d-a137-4ac6-ab71-6c4d4b9b4a33
		summarizeBy: none
		sourceColumn: workbase_name

		annotation SummarizationSetBy = Automatic

	column active
		dataType: string
		lineageTag: 39b83c7e-38ae-422c-8347-b10901119c90
		summarizeBy: none
		sourceColumn: active

		annotation SummarizationSetBy = Automatic

	partition app_employees_workbase = m
		mode: import
		queryGroup: dimension
		source =
				let
				    Source = Odbc.DataSource(Source_odbc, [HierarchicalNavigation=true]),
				    defaultdb_Database = Source{[Name=Database,Kind="Database"]}[Data],
				    public_Schema = defaultdb_Database{[Name="public",Kind="Schema"]}[Data],
				    app_employees_workbase_Table = public_Schema{[Name="app_employees_workbase",Kind="Table"]}[Data],
				    #"Removed Other Columns" = Table.SelectColumns(app_employees_workbase_Table,{"id", "name", "active"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Removed Other Columns",{{"id", "workbase_id"}, {"name", "workbase_name"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

