table Dim_Title1
	lineageTag: 07233fc0-302c-438c-9163-ed05572bb0a7

	column Title1
		dataType: string
		lineageTag: 9b0199d5-7a29-4a65-a660-b796f5acb91d
		summarizeBy: none
		sourceColumn: Title1
		sortByColumn: SortOrder

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column SortOrder
		dataType: int64
		formatString: 0
		lineageTag: 335a2d15-3129-455b-aeec-86b4ee6c2261
		summarizeBy: none
		sourceColumn: SortOrder

		annotation SummarizationSetBy = Automatic

	partition Dim_Title1 = m
		mode: import
		source =
				let
				    Source = #"Ministry Staffing",
				    #"Removed Other Columns" = Table.SelectColumns(Source,{"Title1", "SortOrder"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns")
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

