table dim_category
	lineageTag: bd584173-5664-4416-bb80-52fb2b5f0f1e

	column ID
		dataType: int64
		formatString: 0
		lineageTag: ddede458-2eed-44e5-8e62-6655f87eaf53
		summarizeBy: none
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column Name
		dataType: string
		lineageTag: f63ac39c-a0aa-40fa-9337-881f945ac06a
		summarizeBy: none
		sourceColumn: Name

		annotation SummarizationSetBy = Automatic

	partition dim_category = m
		mode: import
		queryGroup: dimension
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUQpJTUzOSC1SitWJVjIC8v3y83ThYrEA", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [ID = _t, Name = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"ID", Int64.Type}, {"Name", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

