table 'Staffing Adjustment'
	lineageTag: e0674a6b-8e54-4273-8540-d24243abe9fe

	column Type
		dataType: string
		lineageTag: 81c5049a-2c77-46d9-a652-85b242661754
		summarizeBy: none
		sourceColumn: Type

		annotation SummarizationSetBy = Automatic

	column FTTE
		dataType: double
		lineageTag: d2860f65-9bf8-4cda-9e36-61a76103696f
		summarizeBy: sum
		sourceColumn: FTTE

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Staffing Adjustment' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WCilKzCtOSy1S8MxT0lEy1DM1UIrVQRL2Ly0BipvrGZgqxcYCAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Type = _t, FTTE = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Type", type text}, {"FTTE", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

