table vws_manager_information
	lineageTag: 466b15e8-ba71-45a5-9ebe-96f63d6e79c9

	column manager_position_id
		dataType: int64
		formatString: 0
		lineageTag: 0b8f1331-c4fe-4ea0-ae2a-8f1ecfc752e6
		summarizeBy: none
		sourceColumn: manager_position_id
		sortByColumn: 'Position Sort order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column manager_position_name
		dataType: string
		lineageTag: 28768d0c-13b3-40b0-add3-661ed625ce91
		summarizeBy: none
		sourceColumn: manager_position_name
		sortByColumn: 'Position Sort order'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column manager_employment_status
		dataType: string
		lineageTag: bd8c125b-59e4-495f-ba00-cb25271f36a1
		summarizeBy: none
		sourceColumn: manager_employment_status

		annotation SummarizationSetBy = Automatic

	column manager_category
		dataType: string
		lineageTag: f5f6d3d3-d536-4b8f-8d0e-68819a6f930d
		summarizeBy: none
		sourceColumn: manager_category

		annotation SummarizationSetBy = Automatic

	column manager_fte
		dataType: double
		lineageTag: 45fe31a0-6b0e-486d-91cd-b35469efc859
		summarizeBy: sum
		sourceColumn: manager_fte

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column manager_workbase
		dataType: int64
		formatString: 0
		lineageTag: e5b2ea58-0c80-43b7-8509-8fb6eaae55d5
		summarizeBy: sum
		sourceColumn: manager_workbase

		annotation SummarizationSetBy = Automatic

	column manager_name
		dataType: string
		lineageTag: ee66821f-2ad7-4cde-81f4-d5123e6d75e6
		summarizeBy: none
		sourceColumn: manager_name

		annotation SummarizationSetBy = Automatic

	column 'Position Sort order'
		dataType: string
		lineageTag: 92b959c7-eb39-4e7b-80ba-34ffd0a71ab9
		summarizeBy: none
		sourceColumn: Position Sort order

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column primary_holder
		dataType: string
		lineageTag: 2d2cfcc7-c89f-4edc-9616-6b4f2feb032a
		summarizeBy: none
		sourceColumn: primary_holder

		annotation SummarizationSetBy = Automatic

	partition vws_manager_information = m
		mode: import
		queryGroup: dimension
		source =
				let
				    Source = Odbc.DataSource(Source_odbc, [HierarchicalNavigation=true]),
				    defaultdb_Database = Source{[Name="defaultdb",Kind="Database"]}[Data],
				    public_Schema = defaultdb_Database{[Name="public",Kind="Schema"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(public_Schema, each ([Name] = "vws_manager_view")),
				    vws_manager_view_View = #"Filtered Rows"{[Name="vws_manager_view",Kind="View"]}[Data],
				    #"Trimmed Text" = Table.TransformColumns(vws_manager_view_View,{{"manager_position_name", Text.Trim, type text}}),
				    #"Added Custom" = Table.AddColumn(#"Trimmed Text", "Position Sort order", each if [manager_position_name] = "Head of Regional Outreach Services" then 1 else if [manager_position_name] = "Regional Leader" then 2 else if [manager_position_name] = "Outreach Team Lead" then 3 else 99),
				    #"Sorted Rows" = Table.Sort(#"Added Custom",{{"Position Sort order", Order.Ascending}})
				in
				    #"Sorted Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

