table vws_credential_fact
	lineageTag: bd3224d2-f315-4a03-9678-606838658a3c

	column credential_id
		dataType: int64
		formatString: 0
		lineageTag: e0991c55-8df4-42bc-aa6f-9d5fec12abf4
		summarizeBy: sum
		sourceColumn: credential_id

		annotation SummarizationSetBy = Automatic

	column employee_id
		dataType: int64
		formatString: 0
		lineageTag: bb2b988b-2834-46fc-af04-6f26513ba075
		summarizeBy: none
		sourceColumn: employee_id

		annotation SummarizationSetBy = Automatic

	column credential_date_issued
		dataType: dateTime
		formatString: Short Date
		lineageTag: 4339b65e-28ff-4d7a-94de-f539ac28e1a2
		summarizeBy: none
		sourceColumn: credential_date_issued

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column credential_date_expired
		dataType: dateTime
		formatString: Short Date
		lineageTag: 1a7a320d-cca9-4821-adbf-6de9a7439b80
		summarizeBy: none
		sourceColumn: credential_date_expired

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column credential_provider
		dataType: string
		lineageTag: 2eaa7dcf-f092-4f35-89be-a32eeb02671f
		summarizeBy: none
		sourceColumn: credential_provider

		annotation SummarizationSetBy = Automatic

	column credential_type_id
		dataType: int64
		formatString: 0
		lineageTag: e4a621b5-febb-4e60-8bd4-ebfd95a111e1
		summarizeBy: none
		sourceColumn: credential_type_id

		annotation SummarizationSetBy = Automatic

	column employment_detail_start_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: f8ac6c2b-de45-46cf-8093-618d9ef0d29a
		summarizeBy: none
		sourceColumn: employment_detail_start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column employment_detail_end_date
		dataType: dateTime
		formatString: Short Date
		lineageTag: ece9dc97-78aa-4843-b84a-d7d16fb25a86
		summarizeBy: none
		sourceColumn: employment_detail_end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column position_id
		dataType: int64
		formatString: 0
		lineageTag: 664d59a3-89ed-4508-ab61-2e1acb1774f1
		summarizeBy: none
		sourceColumn: position_id

		annotation SummarizationSetBy = Automatic

	column employment_type
		dataType: string
		lineageTag: 3a8b2880-fc15-4b5d-854e-6737ea755e3e
		summarizeBy: none
		sourceColumn: employment_type

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 91f33491-19fb-4bf5-90ca-23e40c9f7afc
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	column days_to_expiry
		dataType: int64
		formatString: 0
		lineageTag: e28eca67-6ad1-4c61-a253-21966ea46efd
		summarizeBy: sum
		sourceColumn: days_to_expiry

		annotation SummarizationSetBy = Automatic

	column expiry_bin
		dataType: string
		lineageTag: a0b03449-dcc4-4432-9224-fb66c27967ae
		summarizeBy: none
		sourceColumn: expiry_bin

		annotation SummarizationSetBy = Automatic

	column employment_status
		dataType: string
		lineageTag: 9221d2c3-6d33-4242-a2b0-32ef0c730676
		summarizeBy: none
		sourceColumn: employment_status

		annotation SummarizationSetBy = Automatic

	column workbase_id
		dataType: int64
		formatString: 0
		lineageTag: 4474871b-0bff-4982-b7a9-4639410ce028
		summarizeBy: none
		sourceColumn: workbase_id

		annotation SummarizationSetBy = Automatic

	partition vws_credential_fact = m
		mode: import
		queryGroup: facts
		source =
				let
				    Source = Odbc.DataSource(Source_odbc, [HierarchicalNavigation=true]),
				    defaultdb_Database = Source{[Name=Database,Kind="Database"]}[Data],
				    public_Schema = defaultdb_Database{[Name="public",Kind="Schema"]}[Data],
				    vws_credential_fact_View = public_Schema{[Name="vws_credential_fact",Kind="View"]}[Data],
				    #"Replaced Value" = Table.ReplaceValue(vws_credential_fact_View,"1","Teacher",Replacer.ReplaceText,{"category"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","0","Non-Teacher",Replacer.ReplaceText,{"category"})
				in
				    #"Replaced Value1"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

